CREATE DATABASE animalia;
USE animalia;

CREATE TABLE pet(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(150) NOT NULL,
monthlyCost FLOAT NOT NULL,
kind ENUM('FISH', 'REPTILE', 'DOG', 'CAT', 'BIRD') DEFAULT 'DOG',
size ENUM('MINI', 'SMALL', 'MEDIUM', 'BIG', 'GIANT') DEFAULT 'MEDIUM', 
);

CREATE TABLE tutor(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(150) NOT NULL,
cpf VARCHAR(20) NOT NULL,
birthday DATE NOT NULL,
remuneration FLOAT NOT NULL,
home_kind ENUM('HOUSE','APARTMENT','HOUSE_WITH_YARD','HOUSE_WITH_POOL','FARM') DEFAULT 'HOUSE',
pet_id BIGINT NOT NULL,
FOREIGN KEY(pet_id) REFERENCES pet(id)
);
